### ISSUE TITLE
CCR4 is sown in the results table but the bar plot says it is not found in the database

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/TargetRanger#10]
<img width="1524" alt="Screen Shot 2023-05-15 at 1 47 24 PM" src="https://github.com/MaayanLab/TargetRanger/assets/12749033/c2179e89-1b67-4763-b739-c0f493ab0f8d">

**Comment by giacomomarino** [comment]
These are the results for the target identification comparing the example file to the GTEx background so it is theoretically possible for a gene to be in GTEx and not in ARCHS4. I found that odd though and found the inconsistency to be the mappings of synonyms (sourced from NCBI) from the ARCHS4 vs. GTEx files. The ARCHS4 gene stats file contains the gene symbol CCR4, but this is mapped to CNOT6 through the NCBI synonym mappings, while in the GTEx gene stats file, which is all Ensembl ids, the Ensembl id ENSG00000183813 is mapped to CCR4 from the same mappings.
