### ISSUE TITLE
Add full name of cancer type yo the dropdown

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/TargetRanger#9]
Also change "Type" to "Cancer type"
<img width="1424" alt="Screen Shot 2023-04-19 at 8 40 07 PM" src="https://user-images.githubusercontent.com/12749033/233228464-ea851742-ab46-4616-96b5-d6265a9649ed.png">

**Comment by AviMaayan** [comment]
Complete names can be found here: https://gdc.cancer.gov/resources-tcga-users/tcga-code-tables/tcga-study-abbreviations

**Comment by giacomomarino** [comment]
add full cancer type names to autocomplete: 08ae7aa
